### ISSUE TITLE
Update / Delete events seem not to be shown despite of k8s-all-events configuration on Slack Channel

### ISSUE THREAD

**Issue by kworkbee** [kubeshop/botkube#1015]
## Description

In the basic configuration of k8s-all-events, `values.yaml` was set so that all messages for the four events can be seen on the Slack channel by adding Update event, but nevertheless, only create/error events are seen on the Slack channel.

## Expected behavior

- 4 events must be shown on Slack Channel.

## Actual behavior

- Only Create / Error events could be found on Slack Channel.

## Steps to reproduce

`k8s-all-events` watches `event.types=all`.

**Comment by kworkbee** [comment]
Hi @josefkarasek, here is what I declared below:

`values.yaml`

```yaml
existingCommunicationsSecretName: "botkube-secret"

sources:
    "k8s-all-events":
      kubernetes:
        namespaces: &k8s-events-namespaces
          include:
            - ".*"
          exclude:
            - "kube-.*"
            - "karpenter"
            - "test"
            
        event:
          types:
            - all

        resources:
          - type: v1/pods
          - type: v1/services
          - type: networking.k8s.io/v1/ingresses
          - type: argoproj.io/v1alpha1/rollouts
```

`botkube-secret (comm_config.yaml)`

```yaml
communications:
  default-group:
    socketSlack:
      enabled: true
      channels:
        default:
          name: {CHANNEL_ID}
          bindings:
            sources:
              - k8s-all-events
```

**Comment by josefkarasek** [comment]
Hi @kworkbee, I haven't been able to reproduce the issue. I used botkube v0.18.0 with your configuration and the following commands:
```
$ k create cm test-1
configmap/test-1 created
$ k label cm test-1 key=val
configmap/test-1 labeled
```

In your testing,  are you emitting update events that actually result in updated kubernetes resource?

#### Possible solution

Botkube filters out update events when the new and old resources are identical:

https://github.com/kubeshop/botkube/blob/02abb23c4c0a9af0afdac7cb9021823fe081945e/internal/source/kubernetes/registration.go#L300-L309

Potentially you can hard-code which fields you want to include in the filter. For example:

https://github.com/kubeshop/botkube/blob/02abb23c4c0a9af0afdac7cb9021823fe081945e/helm/botkube/values.yaml#L251-L255

Let me know if this helps.

**Comment by kworkbee** [comment]
Sorry @josefkarasek, I still have trouble suffering the same issue.
I intend not to watch `ConfigMap`, so it won't work.

I also use v0.18.0, and in the result of dry-run, the following values can be found in the global config below.

```yaml
## global-config
  sources:
      k8s-all-events:
        displayName: Kubernetes Info
        kubernetes:
          annotations: {}
          event:
            message: ""
            reason: ""
            types:
            - all
          labels: {}
          namespaces:
            exclude:
            - kube-.*
            - karpenter
            - test
            include:
            - .*
          resources:
          - type: v1/pods
          - type: v1/services
          - type: networking.k8s.io/v1/ingresses
          - type: argoproj.io/v1alpha1/rollouts
      k8s-create-events:
        displayName: Kubernetes Resource Created Events
        kubernetes:
          event:
            types:
            - create
          namespaces:
            include:
            - .*
          resources:
          - type: v1/pods
          - type: v1/services
          - type: networking.k8s.io/v1/ingresses
          - type: v1/nodes
          - type: v1/namespaces
          - type: v1/configmaps
          - type: apps/v1/deployments
          - type: apps/v1/statefulsets
          - type: apps/v1/daemonsets
          - type: batch/v1/jobs
      k8s-err-events:
        displayName: Kubernetes Errors
        kubernetes:
          event:
            types:
            - error
          namespaces:
            include:
            - .*
          resources:
          - type: v1/pods
          - type: v1/services
          - type: networking.k8s.io/v1/ingresses
          - type: v1/nodes
          - type: v1/namespaces
          - type: v1/persistentvolumes
          - type: v1/persistentvolumeclaims
          - type: v1/configmaps
          - type: rbac.authorization.k8s.io/v1/roles
          - type: rbac.authorization.k8s.io/v1/rolebindings
          - type: rbac.authorization.k8s.io/v1/clusterrolebindings
          - type: rbac.authorization.k8s.io/v1/clusterroles
          - type: apps/v1/deployments
          - type: apps/v1/statefulsets
          - type: apps/v1/daemonsets
          - type: batch/v1/jobs
      k8s-err-with-logs-events:
        displayName: Kubernetes Errors for resources with logs
        kubernetes:
          event:
            types:
            - error
          namespaces:
            include:
            - .*
          resources:
          - type: v1/pods
          - type: apps/v1/deployments
          - type: apps/v1/statefulsets
          - type: apps/v1/daemonsets
          - type: batch/v1/jobs
      k8s-recommendation-events:
        displayName: Kubernetes Recommendations
        kubernetes:
          recommendations:
            ingress:
              backendServiceValid: true
              tlsSecretValid: true
            pod:
              labelsSet: true
              noLatestImageTag: true
```

Since communication config uses `SealedSecret`, the values point to the secret and it consists of the following:

```yaml
communications:
  default-group:
    socketSlack:
      enabled: true
      channels:
        default:
          name: {channelID}
          bindings:
            sources:
              - k8s-recommendation-events
              - k8s-all-events
      botToken: {token}
      appToken: {token}
      notification:
        type: short

  mattermost:
    enabled: false

  teams:
    enabled: false

  discord:
    enabled: false

  elasticsearch:
    enabled: false

  webhook:
    enabled: false

```

Really sorry but please can you re-produce this issue again? Still I can found that configuration above shows me events of [Pod create event, Pod / Node Error] only. Any update or delete events occurred despite of my retries.

I will provide the whole Helm value again. However, due to the company's security issue, some data were blinded.

```yaml
botkube:
  image:
    registry: ghcr.io
    repository: kubeshop/botkube
    pullPolicy: IfNotPresent
    tag: v0.18.0

  podSecurityPolicy:
    enabled: false

  securityContext:
    runAsUser: 101
    runAsGroup: 101

  containerSecurityContext:
    privileged: false
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true

  rbac:
    create: true
    rules:
      - apiGroups: ["*"]
        resources: ["*"]
        verbs: ["get", "watch", "list"]
    staticGroupName: &static-group-name "botkube-plugins-default"

  kubeconfig:
    enabled: false
    base64Config: ""
    existingSecret: ""

  sources:
    "k8s-recommendation-events":
      displayName: "Kubernetes Recommendations"
      kubernetes:
        recommendations:
          pod:
            noLatestImageTag: true
            labelsSet: true
          ingress:
            backendServiceValid: true
            tlsSecretValid: true
    "k8s-all-events":
      displayName: "Kubernetes Info"
      kubernetes:
        namespaces: &k8s-events-namespaces
          include:
            - ".*"
          exclude:
            - "kube-.*"
            - "karpenter"
            - "test"
        event:
          types:
            - all
        annotations: {}
        labels: {}
        resources:
          - type: v1/pods
          - type: v1/services
          - type: networking.k8s.io/v1/ingresses
          - type: argoproj.io/v1alpha1/rollouts
    "prometheus":
      botkube/prometheus:
        enabled: false
        config:
          url: "http://thanos-query-frontend.monitor:9090"
          ignoreOldAlerts: true
          alertStates: ["firing", "pending", "inactive"]
          log:
            level: info

  filters:
    kubernetes:
      objectAnnotationChecker: true
      nodeEventsChecker: true

  existingCommunicationsSecretName: "botkube-communication-secret"

  settings:
    clusterName: {clusterName}

    lifecycleServer:
      enabled: true
      port: 2113

    healthPort: 2114
    upgradeNotifier: true

    log:
      level: info
      disableColors: false

    systemConfigMap:
      name: botkube-system

  ssl:
    enabled: false
    existingSecretName: ""
    cert: ""

  service:
    name: metrics
    port: 2112
    targetPort: 2112

  ingress:
    create: false
    annotations:
      kubernetes.io/ingress.class: nginx
    host: "HOST"
    tls:
      enabled: false
      secretName: ""

  serviceMonitor:
    enabled: false
    interval: 10s
    path: /metrics
    port: metrics
    labels: {}

  deployment:
    annotations: {}

  replicaCount: 1
  extraAnnotations: {}
  extraLabels: {}
  priorityClassName: ""

  nameOverride: ""
  fullnameOverride: ""

  resources: {}

  extraEnv: []

  extraVolumes: []

  extraVolumeMounts: []

  nodeSelector: {}

  tolerations: []

  affinity: {}

  serviceAccount:
    create: true
    name: ""
    annotations: {}

  extraObjects: []
  analytics:
    disable: false

  configWatcher:
    enabled: true
    tmpDir: "/tmp/watched-cfg/"
    initialSyncTimeout: 0
    image:
      registry: ghcr.io
      repository: kubeshop/k8s-sidecar # kiwigrid/k8s-sidecar:1.19.5 - see https://github.com/kubeshop/k8s-sidecar/pull/1
      tag: ignore-initial-events
      pullPolicy: IfNotPresent

  plugins:
    cacheDir: "/tmp"
    repositories:
      botkube:
        url: https://github.com/kubeshop/botkube/releases/download/v0.18.0/plugins-index.yaml
```
