### ISSUE TITLE
Serve DMs to BotKube in Slack

### ISSUE THREAD

**Issue by jayzandme** [kubeshop/botkube#1024]
## Overview
Allow for direct messaging kubectl queries to BotKube with Slack

## Acceptance Criteria

When I direct message a botkube app in slack associated to a specific cluster with a kubectl query, it should return a response.

## Reason
This would simplify the slack workspace and allow us to reduce the number of slack channels

**Comment by blakeromano** [comment]
Wouldn't we want to be able to let K8s Platform teams decide the method?

For example if we do DMing with read only we can use static creds but if they try and do an update command then they get required to use their own credentials?

We currently only let teams via kubectl have access to their own namespace but BotKube allows teams to go look at anyone's namespace and we are fine with that read-only privilege expansion with BK.

**Comment by mszostok** [comment]
@blakeromano 

For now we have only the channel mapping:
```yaml
channels:
  'default':
    # -- Slack channel name without '#' prefix where you have added Botkube and want to receive notifications in.
    name: 'SLACK_CHANNEL'
    bindings:
      # -- Executors configuration for a given channel.
      executors:
        - k8s-default-tools
      # -- Notification sources configuration for a given channel.
      sources:
        - k8s-err-events
        - k8s-recommendation-events
```

we will need to have dedicated binding, sth like:
```yaml
directMessage:
  bindings:
    # -- Executors configuration for a given channel.
    executors:
      - k8s-default-tools
    # -- Notification sources configuration for a given channel.
    sources:
      - k8s-err-events
      - k8s-recommendation-events
```

that's also an option, but it will be sth new to implement and handle 👍 

--- 
BTW @blakeromano @jayzandme is that creating a channel is an issue here? Or more the UX when talking to a bot? So that on the channel, you need to always type the `@Botkube ..` prefix?

What if on your channel you will be able to enable an option type directly the command that you want to run:
`kubectl get po` and Botkube will know that it can handle it and will respond? 

Would that simplify your workflow too?
