### ISSUE TITLE
Kubernetes' recommendation settings ignore the namespace restriction

### ISSUE THREAD

**Issue by mszostok** [kubeshop/botkube#1041]
## Description

With such configuration:
```yaml
  'k8s-backend-err-events':
    displayName: "Kubernetes Errors"
    botkube/kubernetes:
      context: &default-plugin-context
        defaultNamespace: "default"
        rbac:
          group:
            type: Static
            static:
              values: [ "botkube-plugins-default" ]
      enabled: true
      config:
        recommendations: &recommendations
          pod:
            noLatestImageTag: true
            labelsSet: true
          ingress:
            backendServiceValid: true
            tlsSecretValid: true

        namespaces:
          include:
            - "backend"
        event:
          types:
            - error
        resources: &err-resources
          - type: v1/pods
          - type: v1/services
          - type: networking.k8s.io/v1/ingresses
```

we still get recommendation about resources from all namespace.

## Expected behavior

I get only recommendations for namespaces specified under `namespaces` property.
