### ISSUE TITLE
Automated actions don't work with the `ChannelName` RBAC

### ISSUE THREAD

**Issue by mszostok** [kubeshop/botkube#1045]
## Overview

With such example configuration:
```yaml
executors:
  k8s-cli-tools:
    botkube/helm:
      enabled: true
      context:
        rbac:
          group:
            type: ChannelName

actions:
  'check-helm-release':
    enabled: true
    displayName: Display Helm release notes
    command: helm get notes {{ trimPrefix "sh.helm.release.v1." (trimSuffix ".v1"  .Event.Name) }} -n {{.Event.Namespace}}
    bindings:
      sources:
        - detect-helm-release
      executors:
        - k8s-cli-tools
```

You will observe that the action was rendered and executed. However, you will see that you don't have permissions to run it.

## Acceptance Criteria

1. Detect and block `ChannelName` usage in executor configuration.
  -  return human-readable error with suggestion how to fix it.
2. Update documentation to describe our RBAC policy for actions.

### Later

Wait for user feedback and if requested add support for the `ChannelName` RBAC is used for executor under actions. Maybe it would be worth to get the channel name directly from triggered source. However, let's wait for real use-cases.

## Reason

Improve UX.
