### ISSUE TITLE
Pod created notification is still sent for excluded namespace.

### ISSUE THREAD

**Issue by Jelle7** [kubeshop/botkube#1049]
## Description
I've added the jenkins namespace to the list of excluded namespaces but I still see the v1/pods created event coming in on Slack. I use jenkins* now but I had the same issue just using `jenkins`

I am using `v1.0.0` deployed with helm.

## Expected behavior
No notifications should come in for this namespace

## Actual behavior
Notifications do come in for Pod creation

## Steps to reproduce
Config:

```
sources:
    k8s-all-events:
        displayName: Kubernetes Info
        botkube/kubernetes:
            enabled: true
            config:
                annotations: {}
                event:
                    message:
                        exclude: []
                        include: []
                    reason:
                        exclude: []
                        include: []
                    types:
                        - create
                        - delete
                        - error
                filters:
                    nodeEventsChecker: true
                    objectAnnotationChecker: true
                labels: {}
                namespaces:
                    exclude:
                        - jenkins*
                    include:
                        - .*
```

```
    k8s-create-events:
        displayName: Kubernetes Resource Created Events
        botkube/kubernetes:
            enabled: true
            config:
                event:
                    types:
                        - create
                namespaces:
                    exclude:
                        - jenkins*
                    include:
                        - .*
```

```
        socketSlack:
            enabled: true
            channels:
                default:
                    name: botkube
                    notification:
                        disabled: false
                    bindings:
                        sources:
                            - k8s-err-events
                            - k8s-recommendation-events
                            - k8s-all-events
                        executors:
                            - k8s-default-tools
```
