### ISSUE TITLE
Investigate Cloud Slack issue with missing source events

### ISSUE THREAD

**Issue by pkosiec** [kubeshop/botkube#1109]
## Description

For some reason, when using Cloud Slack, notification events + action output messages didn't arrive for Maria's and my instances (even in separate organizations). Like some source bindings for the channel were wrong. But the GraphQL payload looked good to me.

- As @mashby2022 reported, it stopped working like right before the demo.
- Executor commands were still working properly (they are routed via our infra). So the executor config is OK.
- Automation was properly executed as we could see that in logs.
- No errors in logs, however we didn't have time to turn on debug logging.
- I was able to get the events when using Socket Slack though

Super weird -  the event notifications are handled the same way as on Socket Slack (they're not passed through Cloud infra...)

Try to reproduce the error against prod:
- Create new Cloud Slack instance with Kubernetes source (default config watches for errors)
- Connect it on any k8s cluster
- Create automation with kubectl describe or something, bind the K8s source
- Apply resource which is failing, e.g.

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: failing-test
spec:
  containers:
  - name: test
    image: alpine:3
    command: ["/bin/sh"]
    args:
      - "-c"
      - "echo \"$(date -u) Loading configuration...\nstacktrace from panic: \ngoroutine 1 [running]:\nruntime/debug.Stack(0x1042ff18, 0x98b2, 0xf0ba0, 0x17d048)\n    /usr/local/go/src/runtime/debug/stack.go:24 +0xc0\nmain.main.func1()\n    /tmp/sandbox973508195/main.go:11 +0x60\npanic(0xf0ba0, 0x17d048)\n    /usr/local/go/src/runtime/panic.go:502 +0x2c0\nmain.main()\n    /tmp/sandbox973508195/main.go:16 +0x60\n        exit 1\""
```

- Observe no notification, but still a log entry about automation
