### ISSUE TITLE
helm chart options for specifying webhook configuration do not apply settings to the configMap

### ISSUE THREAD

**Issue by messedupryan** [kubeshop/botkube#1195]
## Description

helm chart options to specify webhook configuration do not seem to update the `-runtime-config` configmap properly. This behavior affects using a `values.yaml` and using the `--set communications.default-group.webhook.enabled=true` method.

## Expected behavior

Running a `kubectl get cm botkube-runtime-config -o yaml -n botkube` should have a webhook block in the communications.default-group section.

## Actual behavior
The defailt-group does not contain any webhook configuration.

```
    communications:
      default-group:
        discord:
          channels:
            default:
              bindings:
                sources:
                - k8s-err-events
                - k8s-recommendation-events
        mattermost:
          channels:
            default:
              bindings:
                sources:
                - k8s-err-events
                - k8s-recommendation-events
        slack:
          channels:
            default:
              bindings:
                sources:
                - k8s-err-events
                - k8s-recommendation-events
        socketSlack:
          channels:
            default:
              bindings:
                sources:
                - k8s-err-events
                - k8s-recommendation-events
        teams:
          bindings:
            sources:
              - k8s-err-events
              - k8s-recommendation-events
```

## Steps to reproduce

1. Create a `values.yaml` with the following:
```yaml
communications:
  'default-group':
    webhook:
      enabled: true
      url: http://echoserver-echo-server
      bindings:
        sources:
          - k8s-all-events
```
2. apply this value using helm: 
`helm install --version v1.3.0 botkube --namespace botkube --create-namespace values.yaml botkube/botkube`
