### ISSUE TITLE
Implement ArgoCD source plugin

### ISSUE THREAD

**Issue by pkosiec** [kubeshop/botkube#1238]
## Description

- [x] how to integrate with Argo:
         - webhooks? 
         - custom trigger?
         - custom polling for Argo events
- [x] simplify subscribing for events, instead of require creating configmaps, secrets, templates, we should sth like:
      ```yaml
       on:
         - type: "app-synced":
             enabled: true
             apps: ['foo', 'bar']
             namespace:
               include: ["foo"]
      ```
- [x] simple, but usable implementation (e.g. we can postpone some fancy stuff for later)
- [ ] #1250
