### ISSUE TITLE
Kubernetes nesting overrides don't work with multiple defined resources

### ISSUE THREAD

**Issue by mszostok** [kubeshop/botkube#1251]
## Description

Botkube Kubernetes source doesn't respect nested overrides when multiple resources are provides, for example:
```yaml
        namespaces:
          include:
            - ".*"
        event:
          types:
            - delete
            - error
        resources:
          - type: v1/configmaps
            namespaces:
              include:
                - ".*"
              exclude:
                - "gitlab-runner"
          - type: rbac.authorization.k8s.io/v1/roles
          - type: apps/v1/deployments
```

However, when you have only one resource, then it works as expected, for example:
```yaml
        namespaces:
          include:
            - ".*"
        event:
          types:
            - delete
            - error
        resources:
          - type: v1/configmaps
            namespaces:
              include:
                - ".*"
              exclude:
                - "gitlab-runner"
```
