### ISSUE TITLE
Botkube/doctor request to OpenAI 404:invalid_request_error

### ISSUE THREAD

**Issue by ruudjutinant** [kubeshop/botkube#1350]
## Description
I have been trying to use a doctor, and I got this error.
```
[404:invalid_request_error] Unknown request URL: POST /v1/chat/engines/gpt-3.5-turbo-1106/completions. Please check the URL for typos, or see the docs at https://platform.openai.com/docs/api-reference/.
```
I found that in an OpenAI document, it seems like there is no API with an engine in the path https://platform.openai.com/docs/api-reference/chat. Am I using the wrong configuration, or is it a bug that needs to be fixed?

I'm using Botkube on version v1.7.0 

## Steps to reproduce
this is my AI config
```
  ai:
    botkube/doctor:
      enabled: true
      context: *default-plugin-context
      config:
        apiKey: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
        apiBaseUrl: "https://api.openai.com/v1/chat/"
        defaultEngine: "gpt-3.5-turbo-1106"
        organizationID: ""
        userAgent: ""
```

**Comment by mszostok** [comment]
Hi @ruudjutinant!

There is a [PR](https://github.com/kubeshop/botkube/pull/1349/files) that will fix the default engine because the model we use was shut down (source: https://platform.openai.com/docs/deprecations/2023-07-06-gpt-and-embeddings).

For now, you can use different model with the configuration settings:  https://docs.botkube.io/configuration/executor/doctor#syntax

Please try using `gpt-3.5-turbo-instruct`:

```yaml
  ai:
    botkube/doctor:
      enabled: true
      context: *default-plugin-context
      config:
        apiKey: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
        apiBaseUrl: "https://api.openai.com/v1/chat/"
        defaultEngine: "gpt-3.5-turbo-instruct"
        organizationID: ""
        userAgent: ""
```
