### ISSUE TITLE
Helm upgrade with `existingCommunicationsSecretName` fails

### ISSUE THREAD

**Issue by pkosiec** [kubeshop/botkube#1376]
_Originally posted by @voriol in https://github.com/kubeshop/botkube/issues/1274#issuecomment-1933520800_
            
---

When updating my helm chart to the latest version, 1.8.0 I got the following error:

_**Error: template: sre-botkube/charts/botkube/templates/persistent-config.yaml:6:23: executing "sre-botkube/charts/botkube/templates/persistent-config.yaml" at <index $secret.data "comm_config.yaml">: error calling index: index of untyped nil**_

Reviewing the latest changes I see that the line it refers to was changed in this commit

https://github.com/kubeshop/botkube/commit/fdb389c12600e194e503aaa1eb4e2a914e93be7b#diff-e694b58be4de3f2b3d147e65317458bbbc0f5319bd07c703d80dc3b05bb5d1b7

Specifically, on line 6:

`{{- $data := b64dec (index $secret.data "comm_config.yaml") -}}`

This is the secret content:

```
apiVersion: v1
kind: Secret
metadata:
  name: botkube-communications
stringData:
  comm_config.yaml: |
    communications:
      default-group:
        ## Settings for Slack with Socket Mode.
        ...etc
```

I am doing something wrong? 

Thanks
