### ISSUE TITLE
[BUG] Botkube can't create index in AWS ElasticSearch 

### ISSUE THREAD

**Issue by soq** [kubeshop/botkube#406]
**Describe the bug**
With version 0.11.0 and AWS ElasticSearch usage I get an error in botkube logs:
`ERRO[2020-10-06T12:50:59Z] Failed to create index. Error:elastic: Error 500 (Internal Server Error): Compressor detection can only be called on some xcontent bytes or compressed xcontent bytes [type=not_x_content_exception]`
and in AWS ELK logs:
`org.elasticsearch.common.compress.NotXContentException: Compressor detection can only be called on some xcontent bytes or compressed xcontent bytes`
So, no index, no logs.

**To Reproduce**
Try to use AWS ELK with botkube 0.11.0 and without awsSigning enabled.

**Expected behavior**
Logs with events in ELK.

**Additional context**
This error was mentioned here https://github.com/olivere/elastic/issues/1082 and described more here https://github.com/olivere/elastic/wiki/Using-with-AWS-Elasticsearch-Service#compression. Here is https://github.com/infracloudio/botkube/blob/v0.11.0/pkg/notify/elasticsearch.go#L86 the place as I can understand where this behaviour could be changed.

**Comment by sushrut111** [comment]
I would like to work on this. I have worked on AWS Elasticsearch and have worked on developing the integration hooks.
However I will need detailed steps for reproducing the issue. Please let me know if I can start working on this.

**Comment by sushrut111** [comment]
I could not reproduce this issue. I used the following ELS config:

```yaml
  elasticsearch:
    enabled: true
    awsSigning:
      enabled: false                          # enable awsSigning using IAM for Elastisearch hosted on AWS, if true make sure AWS environment variables are set. Refer https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html
      awsRegion: 'us-east-1'                  # AWS region where Elasticsearch is deployed
      roleArn: ''                             # AWS IAM Role arn to assume for credentials, use this only if you dont want to use the EC2 instance role or not running on AWS instance
    server: 'xxxx'           # e.g https://example.com:9243
    # ELS index settings
    index:
      name: botkube
      type: botkube-event
      shards: 1
      replicas: 0
```
I disabled the auth totally. 

I will again try with Basic Auth. Meanwhile @soq can you help me with the steps for reproducing the issue?

**Comment by sushrut111** [comment]
Could not reproduce event with basic auth

```yaml
  elasticsearch:
    enabled: true
    awsSigning:
      enabled: false                          # enable awsSigning using IAM for Elastisearch hosted on AWS, if true make sure AWS environment variables are set. Refer https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html
      awsRegion: 'us-east-1'                  # AWS region where Elasticsearch is deployed
      roleArn: ''                             # AWS IAM Role arn to assume for credentials, use this only if you dont want to use the EC2 instance role or not running on AWS instance
    server: 'https://search-anothertestdomain-3akoieanofize5qrim3jmnrbfq.us-east-2.es.amazonaws.com:443'           # e.g https://example.com:9243
    username: 'sushrut'        # Basic Auth
    password: 'xxxxxxx'
    # ELS index settings
    index:
      name: botkube
      type: botkube-event
      shards: 1
      replicas: 0
```

**Comment by soq** [comment]
Hello @sushrut111 !

I use following config:
```YAML
elasticsearch:
  enabled: true
  server: 'https://some_aws_name.eu-west-1.es.amazonaws.com:443'             
  username: ''          
  password: ''
  index:
    name: botkube
    type: botkube-event
    shards: 1
    replicas: 0
```
And we use AWS ElasticSearch version 6.7. 
Here are some related ES parameters that I can see:

```
Allow APIs that can span multiple indices and bypass index-specific access policies: true
Fielddata cache allocation: unbounded (default)
Max clause count: 1024 (default)
```
