### ISSUE TITLE
How to get notify when pod retarts! 

### ISSUE THREAD

**Issue by gauravgola96** [kubeshop/botkube#468]

**Comment by pkosiec** [comment]
Hi @gauravgola96, 
The default configuration already notifies aboud Pod errors and create/delete events:

```yaml
      resources:
        - name: v1/pods             # Name of the resource. Resource name must be in group/version/resource (G/V/R) format
                                    # resource name should be plural (e.g apps/v1/deployments, v1/pods)

          events:                   # List of lifecycle events you want to receive, e.g create, update, delete, error OR all
            - create
            - delete
            - error
```

Hope that helps!

Feel free to reopen the issue f you need further assistance 🙂
