### ISSUE TITLE
add exec

### ISSUE THREAD

**Issue by dashanji** [kubeshop/botkube#499]
Hello，there! Can we enter the node through exec to view some information or execute some scripts ？ Thank you!

**Comment by mszostok** [comment]
Hi
as a part of #841 and https://github.com/kubeshop/botkube/issues/675 you will be able to easily attach a ServiceAccount with a dedicated rule that will allow you to run `exec` on nodes, e.g.:
```
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: exec
rules:
- apiGroups: [""]
  resources: ["exec/exec"]
  verbs: ["create"]
```
