### ISSUE TITLE
Filter Events by JSONPATH

### ISSUE THREAD

**Issue by h4wkmoon** [kubeshop/botkube#559]
resources:
Hi, 
I'm watching my velero backups with botkube. I'd like to have only failures, or partial failures notifications.

I would like to be able to specify a field in the object, by its jsonpath, for example, and the values I want (or do not want) notifications for.

Currently, I can only filter by the CRUD kind of the event. So for a backup, I have CREATE (when the kubernetes object is created), and several updates. Failures and successes are notified the same way.

This would be great also to watch sealedsecret being unsuccessfully unsealed. With a jsonpath filter, in the yaml config file, it would be veeery easy to do great things.

ex for velero:

This would only send notifications for UPDATE event when the field status.phase is not "Completed".
```
      - name: velero.io/v1/backups
        fields:
        - path: status.phase
          exclude: ["Completed"]
        namespaces:
          include:
            - all
        events:
          - update
        updateSetting:
          includeDiff: true
          fields:
            - status.phase

```
