### ISSUE TITLE
[BUG] Node readiness status not triggering an alarm

### ISSUE THREAD

**Issue by clementnuss** [kubeshop/botkube#560]
**Describe the bug**
When nodes transition from `Ready` to `NotReady`, no alarm is sent by botkube.

**To Reproduce**

my configuration file regarding nodes monitoring:
```yaml
        - name: v1/nodes
          namespaces:
            include:
              - all
          events:
            - create
            - delete
            - error
            - update
          updateSetting:
            includeDiff: true
            fields:
              - status.conditions[*]
```
(I have also tried without `update` and `updateSetting`, as per default according to the values.yaml, but without success.

**Expected behavior**
I expect an alarm to be sent when a node changes from Ready to NotReady (and vice versa)

**Additional context**

I did receive an alarm for a node error, but nothing regarding readiness transitions.
<img width="559" alt="Screenshot 2022-01-25 at 22 06 02" src="https://user-images.githubusercontent.com/2116997/151059748-cf030a40-ebda-4424-b1db-f02b896b1b2b.png">

I must be missing the proper config, but couldn't find it in other issues.
