### ISSUE TITLE
Release v0.13.0 summary

### ISSUE THREAD

**Issue by mszostok** [kubeshop/botkube#614]
> **Warning**
> Before upgrading to v0.13.0 get familiar with the below breaking changes list.

The v0.13.0 release has the following breaking changes:
- Syntax for the `communications` property in BotKube Helm chart has changed.

  <table>
  <tr>
  <td> Before v0.13.0 </td> <td> In v0.13.0 </td>
  </tr>
  <tr>
  <td>

    ```yaml
    communications:
      slack:
      ...
      mattermost:
      ...
    ```

  </td>
  <td>

    ```yaml
    communications:
     {name}:
       slack:
       ....
       mattermost:
       ...
    ```

  </td>
  </tr>
  </table>

  **REASON:** It enabled an option to define multiple communication settings for each provider and reference difference settings to each of them.

- Syntax for the `resources` property in BotKube Helm chart has changed.

  <table>
  <tr>
  <td> Before v0.13.0 </td> <td> In v0.13.0 </td>
  </tr>
  <tr>
  <td>

    ```yaml
    config:
      resources:
        - name: v1/pods


    ```

  </td>
  <td>

    ```yaml
    sources:
     {sourceGroupName}:
        - name: v1/pods
     ......
    communications:
     {commName}:
       slack:
         channels:
           {channelName}:
             bindings:
               sources:
                 - {sourceGroupName} 
                 - ...
    ```

  </td>
  </tr>
  </table>

  **REASON:** It enabled an option to define group of kubernetes resources in a way that you can reference one or more resource groups in `communications` section in the configurations.

- Syntax for the `extraEnv` property in BotKube Helm chart has changed.
  <table>
  <tr>
  <td> Before v0.13.0 </td> <td> In v0.13.0 </td>
  </tr>
  <tr>
  <td>

    ```yaml
    extraEnv:
      HTTP_PROXY: <proxyURL>:<port>


    ```

  </td>
  <td>

    ```yaml
    extraEnv:
      - name: HTTP_PROXY
        value: <proxyURL>:<port>
    ```

  </td>
  </tr>
  </table>

   **REASON:** It enabled an option to define more complex environment variable source. For the syntax, see the [environment variable API](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#environment-variables) document.

- Syntax for the `notiftype` property in BotKube Helm chart has changed to `notification.type`.
  <table>
  <tr>
  <td> Before v0.13.0 </td> <td> In v0.13.0 </td>
  </tr>
  <tr>
  <td>

    ```yaml
    communications:
      {name}:
        notiftype: short 

    ```

  </td>
  <td>

    ```yaml
    communications:
      {name}:
        notification:
          type: short 
    ```

  </td>
  </tr>
  </table>

   **REASON:** It enables an option to add more settings for notifications that are sent. For example, enable sending a related message in a thread, or editing a given message in place.

- Syntax for the `clustername` property in BotKube Helm chart has changed to `clusterName`.
   **REASON:** Fix readability and improves consistency with defining environment variable name for this property.

- Syntax for the `botid` property in BotKube Helm chart has changed to `botID`.

   **REASON:** Fix readability and improves consistency with defining environment variable name for this property.

- Syntax for the `configwatcher` property in BotKube Helm chart has changed to `configWatcher`.

   **REASON:** Fix readability and improves consistency with defining environment variable name for this property.

- The `CONFIG_PATH `  was replaced by `BOTKUBE_CONFIG_PATHS`. 

   **REASON:** Get rid of hard-coded config file names. Enable an option to split individual settings into multiple configuration files. The priority will be given to the last (right-most) file specified. Read more at https://botkube.io/configuration/.
