### ISSUE TITLE
Resolve setting array values using environment variables

### ISSUE THREAD

**Issue by pkosiec** [kubeshop/botkube#655]
## Overview

After introducing the new configuration syntax proposal, we need to figure out how to override array items with environment variables.

For example:

```yaml
    communications:
      - name: tenant-b-workspace
        slack:
          token: 'SLACK_API_TOKEN'
```
What env will override this? `BOTKUBE_COMMUNICATION_0_SLACK_TOKEN`, or `BOTKUBE_COMMUNICATION_TENANT_B_WORKSPACE_SLACK_TOKEN`? 

Alternatively, we can change the syntax to:

```yaml
    communications:
      tenantBWorkspace:
        slack:
          token: 'SLACK_API_TOKEN'
          # ...trimmed...
``` 

## Acceptance Criteria

- Investigate possible options and shortly describe them (e.g. in the comment under this issue, or a separate document if necessary)
- Implement the selected solution

## Reason

See epic #596 for details.
