### ISSUE TITLE
Abstract custom filter definitions

### ISSUE THREAD

**Issue by brampling** [kubeshop/botkube#657]
Currently custom [filter definitions](https://botkube.io/filters/) need to be written in Go. They then need to be called from the source code in [with_all_filters.go](https://github.com/kubeshop/botkube/blob/main/pkg/filterengine/with_all_filters.go). The BotKube container then needs to be rebuilt and redeployed.

It would be useful if custom filters could be defined in some abstracted manner (e.g. YAML).

It would also be useful if filter definitions could be kept in a ConfigMap and dynamically loaded.

This would allow:

- Non-developers to build filters
- Filters to be built faster with less boilerplate code
- Users to add filters who do not have access to rebuild/redeploy the BotKube back end

**Comment by brampling** [comment]
#412 related

**Comment by mszostok** [comment]
Initial thoughts:

IMO it would be good to extract the whole K8s source as external “plugin” first and have those filters not as a BotKube functionality but K8s source related **(if still needed).**

In case of BotKube, we can come up with some general mutation/validation webhooks approach.
```yaml
mutators:  # executed in a given order
  # run image
  - image: gcr.io/kpt-fn/set-labels:v0.1.0
    parameters:
      animal: fish
      name: herring
validators:  # executed in parallel after all mutators
  # or instead of image, call external service
  - url: example-service.default.svc.cluster.local:9111/v1/validate
```

As a result, BotKube core logic will be fairly simple and more “generic” as it can work with any sources (not only k8s).

Additional thing is that the webhooks should be connected with a given “event”. Probably we should define [CloudEvents](https://cloudevents.io/)  schema to have some common fields on all sources’ events and require from them to sent event name e.g. `<source_name>.<event_type>.<event_name>`. 

In case of k8s, the event name could be `kubernetes.resources.pod`. In that way we could add mutators/validators into the exact event (`kubernetes.resources.pod `) or for a group of them (`kubernetes.resources.*`).

It’s a draft idea, but I hope that you see the direction. Additionally, maybe it should work in both ways, not only `sources -> webhooks -> communication platform` but also `communication platform -> webhooks -> executors` - but this sounds like a feature that we don’t need right now.
