### ISSUE TITLE
Add logic to handle communicator bindings in `kubectl`

### ISSUE THREAD

**Issue by mszostok** [kubeshop/botkube#668]
## Overview

Add logic to use settings with from given bindings.(blocked by #666) Proposed merge strategy:

**Policy**

- merge only if enabled `kubectl.enabled == true`
- the merge appends the items of
	- `kubectl.commands.verbs`
	- `kubectl.commands.resources`
		Only if the allowed Namespace is matched.

```yaml
bindings:
  executors:
    - 'kubectl-team-a'
    - 'kubectl-team-b'
    - 'kubectl-global'
    -  'kubectl-exec'
executors:
  'kubectl-team-a':
    kubectl:
      namespaces:
        include: [ "team-a" ]
      commands:
        verbs: [ "get" ]
        resources: [ "deployments" ]
  'kubectl-team-b':
    kubectl:
      namespaces:
        include: [ "team-b" ]
      commands:
        verbs: [ "get", "describe" ]
        resources: [ "deployments", "pods" ]
  'kubectl-global':
    kubectl:
      namespaces:
        include: [ "all" ]
      commands:
        verbs: [ "logs", "top" ]
        resources: [ ]
  'kubectl-exec':
    kubectl:
      enabled: false
      namespaces:
        include: [ "all" ]
      commands:
        verbs: [ "exec" ]
        resources: [ ]
```

## Acceptance Criteria

- `kubectl` executor works only if there is a given binding
- if there are multiple bindings for a given channel, apply merging strategy and execute `kubectl`

## Reason

See https://github.com/kubeshop/botkube/issues/596
