### ISSUE TITLE
Resources configured with blank events are causing incorrect debug logs

### ISSUE THREAD

**Issue by ezodude** [kubeshop/botkube#671]
## Description

This is a minor issue that complicates event and Informer debugging.

It was discovered when investigating #570. The root cause is event configuration that looks like this:
```yaml
sources:
  'k8s-events':
    recommendations: true
    kubernetes:
      resources:
        - name: apps/v1/deployments
          namespaces:
            include:
              - all
            ignore:
              -
          events:
            -
```

### The issue

- Events are parsed as an array with single value.
- That single value is a blank string.
- Various parts that register Informer Handlers, assume there are valid events in the array.
- This causes incorrect info to be written out to the logs which complicates debugging.

In actuality, there are no valid Event Types, and NO Informer Handlers are registered.

## Expected behavior

- Events should be parsed as an empty array.
- No Event handler logs should be displayed.

## Actual behavior

- Incorrect log are displayed, confusing application debug.

See the log message below:
```shell
INFO[2022-08-02T10:59:51+01:00] Adding informer for resource "apps/v1/deployments"  component=Controller
```

## Steps to reproduce

Configure events in your sources as follows:

```yaml
sources:
  'k8s-events':
    recommendations: true
    kubernetes:
      resources:
        - name: apps/v1/deployments
          namespaces:
            include:
              - all
            ignore:
              -
          events:
            -
```
