### ISSUE TITLE
Add ability to configure specific recommendations during BotKube installation/upgrade

### ISSUE THREAD

**Issue by pkosiec** [kubeshop/botkube#684]
## Overview

Implement ability to turn on/off recommendations according to the proposal:  https://github.com/kubeshop/botkube/blob/main/docs/proposal/2022-06-14-configuration-bindings.md#new-syntax

```yaml
        # Recommendations about the best practices
        recommendations:
          image:     # "Checks if 'latest' image tag is used for container image."
            enabled: true
          pod:       # "Checks if labels are missing in the pod specs."
            enabled: true
          ingress:   # "Checks if services and tls secrets used in ingress are available."
            enabled: true
```

## Acceptance Criteria

- [x] Support recommendation configuration under `source` and enable/disable proper recommendations during BotKube startup
- [x] Ensure enabling/disabling filters in runtime via `@BotKube` command still works
- [x] Update documentation
- [x] Update merging strategy to "override" to be consistent with `Executor.Kubectl.Commands.RestrictAccess`
- [x] Create informers if recommendations are enabled, even if Ingress and Pod resources are not configured in the resources configuration (blocked by https://github.com/kubeshop/botkube/issues/676)

## Reason

See epic https://github.com/kubeshop/botkube/issues/596
