### ISSUE TITLE
Recommendation-related events are posted even if they shouldn't

### ISSUE THREAD

**Issue by pkosiec** [kubeshop/botkube#735]
## Description

BotKube posts some recommendation-related notifications even if it shouldn't, when a namespaced-isolated configuration is used. 

## AC

- Prepare a fix
    - Make sure it works for both scenarios:
       -  multiple bindings for a single channel
       - same binding for multiple channels 
- Add test case to avoid this in future (unit test will be enough)

## Steps to reproduce

1. Set up `frontend` and `backend` channels in a Slack workspace
1. Create `frontend` and `backend` namespaces in the cluster
1. Use the values.yaml file:

```yaml
communications:
  'default-group':
    # Settings for Slack
    slack:
      enabled: true
      botToken: "xoxb-..."
      appToken: "xapp-..."
      channels:
        'default':
          name: backend
          bindings:
            executors:
              - kubectl-backend
            sources:
              - k8s-backend
        'frontend':
          name: frontend
          bindings:
            executors:
              - kubectl-frontend
            sources:
              - k8s-frontend

settings:
  clusterName: gke-playground

sources:
  'k8s-backend':
    kubernetes:
      recommendations:
        pod:
          noLatestImageTag: true
          labelsSet: true

      namespaces:
        include:
          - "backend"

      resources:
        - name: apps/v1/deployments
          events:
            - create
            - error
        - name: v1/pods
          events:
            - create
            - error
        - name: v1/services
          events:
            - create
            - error

  'k8s-frontend':
    kubernetes:
      recommendations:
        pod:
          noLatestImageTag: false
          labelsSet: false
        ingress:
          backendServiceValid: false
          tlsSecretValid: false

      resources:
        - name: v1/pods
          namespaces:
            include:
              - "frontend"
          events:
            - create
            - error

executors:
  'kubectl-backend':
    kubectl:
      namespaces:
        include:
          - "backend"
      enabled: true
      commands:
        verbs: ["run", "describe", "get", "logs"]
        resources: ["pods","services", "test", "test2"]
      defaultNamespace: backend
      restrictAccess: false
  'kubectl-frontend':
    kubectl:
      namespaces:
        include:
          - "frontend"
      enabled: true
      commands:
        verbs: ["run", "describe", "get", "logs"]
        resources: ["pods","services", "test", "test2"]
      defaultNamespace: frontend
      restrictAccess: false

rbac:
  create: true
  rules:
    - apiGroups: ["*"]
      resources: ["*"]
      verbs: ["get", "watch", "list"]
    - apiGroups: [""]
      resources: ["pods"]
      verbs: ["delete", "create"]

analytics:
  disable: true
```

1. Install BotKube 0.13 or newer (from lastest `main`):

```bash
helm install botkube --version v0.13.0 botkube/botkube --namespace botkube --create-namespace  -f /tmp/values.yaml
```

1. Run from BotKube `frontend` channel:

```
@BotKube run test -n frontend --restart=Never --image=curlimages/curl:7.85.0 -- curl -v --fail foo.bar/non-existing
```

1. See "Pod create" notifications on both channels.

## Expected behavior

Notification is posted only on the `frontend` channel. In `backend` channel it shouldn't be posted as it doesn't contain any recommendation or warning.

## Actual behavior

Notification about Pod creation is posted both in `backend` and `frontend` channels.

## Additional notes

An additional debugging is needed. From what I observed, this logic in controller:

```go
	if recommendation.ShouldIgnoreEvent(recCfg, c.conf.Sources, sources, event) {
		c.log.Debugf("Skipping event as it is related to recommendation informers and doesn't have any recommendations: %#v", event)
		return
	}
```

returns bool for a given event, even if there are two different sources (`k8s-backend` and `k8s-frontend`) used for separate channels. I think we should return there a slice of "allowed" sources, but this is just a part of the problem. We also merge the recommendations config based on sources for a given event. That makes sense for 2 same bindings for the same channel, but in such case we shouldn't do that.
