### ISSUE TITLE
Run E2E tests in parallel

### ISSUE THREAD

**Issue by ezodude** [kubeshop/botkube#749]
To speed up CI builds and pull request builds/reviews we should run the E2E tests in parallel.

To solve this, [two options were suggested](https://github.com/kubeshop/botkube/issues/307#issuecomment-1249681549).

IMO, the simpler and easier to maintain option is: Do away with helm test and run `make test-integration-(integration)` in parallel.

This can be implemented as follows,

- Ensure all required ENV VARS are loaded, including `SLACK_BOT_NAME`.

- Use the [GitHub Actions matrix strategy](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategymatrix) to run `make test-integ...` jobs in parallel.

In practice this means updating `pr-build.yaml` and `branch-build.yaml` with:

```YAML
  ...
  integration-tests:
  ...
  strategy:
      matrix:
        integration:
          - slack
          - discord
  steps:
  ...
    - name: Run tests
      run: "make test-integration-${{ matrix['integration'] }}"
  ...
```
