### ISSUE TITLE
Validate bindings for a given communicator

### ISSUE THREAD

**Issue by mszostok** [kubeshop/botkube#760]
## Description

Currently, we allow specifying unknown bindings under:
```yaml
communications:
 'default':
   {communicator}:
     channels:
       'channel':
         bindings:
           sources:
             - {sourceGroupName}  # here
             - ...
           executors:
             - {executorGroupName}  # here
             - ...

```
However, we should validate whether they exist under:
```yaml
sources:
 {sourceGroupName}: {}

executors:
 {executorGroupName}: {}
```

## Expected behavior

BotKube is not started with invalid configuration.

## Actual behavior

BotKube is started with invalid configuration but sources and executor doesn't work, and user don't have any feedback message why it's not working.

## Notes

Add dedicated validator under: https://github.com/kubeshop/botkube/blob/main/pkg/config/validator.go
