### ISSUE TITLE
Single channel to multiple sources recommendations do not work as expected.

### ISSUE THREAD

**Issue by ezodude** [kubeshop/botkube#763]
## Description

Using the recommendations config below, recommendations do not work as expected.

As an aside, this is not a common issue ... and as a worse case scenario you would receive an unnecessary recommendation when you didn't expect one.

(discovered while working on https://github.com/kubeshop/botkube/issues/735)

```YAML
# /tmp/rec-bug.yaml
communications:
  'default-group':
    # Settings for Slack
    slack:
      enabled: true
      token: "xoxb-"
      channels:
        'default':
          name: backend
          bindings:
            executors:
              - kubectl-backend
            sources:
              - k8s-backend
        'frontend':
          name: frontend
          bindings:
            executors:
              - kubectl-frontend
            sources:
              - k8s-backend
              - k8s-frontend

settings:
  clusterName: gke-playground

sources:
  'k8s-backend':
    kubernetes:
      recommendations:
        pod:
          noLatestImageTag: true
          labelsSet: true

      namespaces:
        include:
          - "backend"

      resources:
        - name: apps/v1/deployments
          events:
            - create
            - error
        - name: v1/pods
          events:
            - create
            - error
        - name: v1/services
          events:
            - create
            - error

  'k8s-frontend':
    kubernetes:
      recommendations:
        pod:
          noLatestImageTag: false
          labelsSet: false
        ingress:
          backendServiceValid: false
          tlsSecretValid: false

      namespaces:
        include:
          - "backend" # I think it doesn't matter as recommendations are enabled/disabled for all namespaces 🤔 

      resources:
        - name: v1/pods
          namespaces:
            include:
              - "frontend"
          events:
            - create
            - error

executors:
  'kubectl-backend':
    kubectl:
      namespaces:
        include:
          - "backend"
      enabled: true
      commands:
        verbs: ["run", "describe", "get", "logs"]
        resources: ["pods","services", "test", "test2"]
      defaultNamespace: backend
      restrictAccess: false
  'kubectl-frontend':
    kubectl:
      namespaces:
        include:
          - "frontend"
      enabled: true
      commands:
        verbs: ["run", "describe", "get", "logs"]
        resources: ["pods","services", "test", "test2"]
      defaultNamespace: frontend
      restrictAccess: false

rbac:
  create: true
  rules:
    - apiGroups: ["*"]
      resources: ["*"]
      verbs: ["get", "watch", "list"]
    - apiGroups: [""]
      resources: ["pods"]
      verbs: ["delete", "create"]

analytics:
  disable: true
```

## Expected behavior

- The backend channel should receive a pod "created" message and included recommendation.
- The frontend channel should receive a pod "created" message BUT NOT the recommendation.

## Actual behavior

- The backend channel receives a pod "created" message and included recommendation.
- The frontend channel receives a pod "created" message and included recommendation.

## Steps to reproduce

Install/upgrade BotKube with config presented in the description.

```shell
helm upgrade botkube --install --namespace botkube ./helm/botkube --create-namespace -f /tmp/rec-bug.yaml
```

On the `backend` slack channel:
```
@BotKube run test-next -n backend --restart=Never --image=curlimages/curl:latest -- curl -v --fail foo.bar/non-existing
```
