### ISSUE TITLE
Configure action automation for a selected incoming event

### ISSUE THREAD

**Issue by ezodude** [kubeshop/botkube#828]
## Overview

[Botkube automation](#789) allows users to execute actions (kubectl commands) based on incoming events. This requires users to add a target command to a specific event in a source.

This issue updates configuration in `values.yaml` to enable this behaviour.

## Acceptance Criteria

- Configuration settings that allow event -> action automation set up.
- Highlight the use of templates in the configured automation actions, to act on dynamic event data.
- Investigate whether the action automation should target multiple events at once to avoid repetition.

## Reason

Part of #789

**Comment by ezodude** [comment]
## DRAFT config

```yaml
## actions, define automations that will be executed on sources.
## For a defined action, it has to be added to a sources resource+event combo for it to run successfully.
## Format: actions.{alias}
actions:
  ## kubectl based action
  'show-created-resource':
    ## Kubectl action configuration - requires that a kubectl executor with correct permission is available
    kubectl:
      enabled: true
      run: "kubectl get {{.Event.ResourceType}} -n {{.Event.Namespace}} {{.Event.Name}}"

  ## helm based action
  'decrease-elastic-cpu-limit':
    ## helm action configuration - requires that a helm executor with correct permission is available
    helm:
      enabled: true
      run: |
        helm upgrade elasticsearch elasticsearch \
        --namespace elastic \
        --set resources.limits.cpu='2G'

sources:
  'k8s-events-one':
    displayName: "Kubernetes Info"
    kubernetes:
      namespaces: &k8s-events-namespaces
        include:
          - ".*"

      events:
        - create:
          # -- Automation actions configuration for a given (resource and) event.
          actions:
            - 'show-created-resource'      # already defined action
        - delete
        - error

      resources:
        - name: v1/pods
        - name: v1/services

  'k8s-err-events':
    displayName: "Kubernetes Errors"

    kubernetes:
      namespaces: *k8s-events-namespaces

      events:
        - error

      resources:
        - name: v1/pods
        - name: v1/services
        - name: networking.k8s.io/v1/ingresses
        - name: v1/nodes
          events:
            - error:
              # -- Automation actions configuration for a given (resource and) event.
              actions:
                - 'decrease-elastic-cpu-limit'      # already defined action for 'v1/nodes' resource + error event
        - name: v1/namespaces
```
