### ISSUE TITLE
Got empty response for: external.metrics.k8s.io/v1beta1

### ISSUE THREAD

**Issue by nguyend91** [kubeshop/botkube#829]
## Description

We're getting error:
`[memcache.go:206] couldn't get resource list for external.metrics.k8s.io/v1beta1: Got empty response for: external.metrics.k8s.io/v1beta1`
...when applying BotKube v0.15.0.

We have [KEDA](https://keda.sh/) deployed across several clusters. What we've found is that BotKube deployment will break if `external.metrics.k8s.io/v1beta1` returns an empty list. We try to keep all of our clusters in-sync, but there are a few clusters that will intermittently use KEDA.

Is there a way we can add "ignore empty lists" logic somewhere? Thanks!

## Expected behavior

```
level=info msg="Using API Key starting with \"xUd\"..." component="Analytics reporter"
level=info msg="Registering filter \"ObjectAnnotationChecker\" (enabled: true)..." component="Filter Engine"
level=info msg="Registering filter \"NodeEventsChecker\" (enabled: true)..." component="Filter Engine"
level=info msg="Starting server on address \":2112\"" component="Metrics server"
level=info msg="Loaded resource mapping: ... component="Resource Name Normalizer"
level=info msg="Skipping waiting for Config Watcher sync..." component="Config Watcher Sync"
level=info msg="Starting bot" bot=Slack commGroup=default-group
level=info msg="Starting server on address \":2113\"" component="Lifecycle server"
level=info msg="Starting controller..." component=Controller
level=info msg="Starting checker" component="Upgrade Checker"
level=info msg="Sending welcome message..." component=Controller
level=info msg="Botkube connected to Slack!" bot=Slack commGroup=default-group
```

## Actual behavior

```
level=info msg="Using API Key starting with \"xUd\"..." component="Analytics reporter"
level=info msg="Registering filter \"ObjectAnnotationChecker\" (enabled: true)..." component="Filter Engine"
level=info msg="Registering filter \"NodeEventsChecker\" (enabled: true)..." component="Filter Engine"
level=info msg="Starting server on address \":2112\"" component="Metrics server"
[E1025 memcache.go:206] couldn't get resource list for external.metrics.k8s.io/v1beta1: Got empty response for: external.metrics.k8s.io/v1beta1
level=info msg=Closing... component="Analytics reporter"
level=info msg="Shutdown requested. Finishing..." component="Metrics server"
while creating resource name normalizer: while getting resource list from K8s cluster: unable to retrieve the complete list of server APIs: external.metrics.k8s.io/v1beta1: Got empty response for: external.metrics.k8s.io/v1beta1
```

## Steps to reproduce

1. Install [KEDA](https://github.com/kedacore/charts/tree/main/keda) (Helm chart).
2. Attempt to install [BotKube](https://github.com/kubeshop/botkube/tree/main/helm/botkube) v0.15.0 (Helm chart).
3. BotKube container will enter `CrashLoopBackOff`.

**Comment by nguyend91** [comment]
I believe this is a similar issue: https://github.com/kyverno/kyverno/issues/2267

**Comment by pkosiec** [comment]
Hi @nguyend91, thank you for reporting the issue. We'll try to investigate that further and fix it in the upcoming release. Thanks for linking the similar issue 👍

**Comment by pkosiec** [comment]
Alright, did a quick research and here are the results:
The error comes from `client-go`: https://github.com/kubernetes/client-go/blob/release-1.25/discovery/cached/memory/memcache.go#L228. I couldn't find any reported issue about such client behavior.

After reading https://github.com/kedacore/keda/issues/1797, looks like KEDA shouldn't return empty resource list 🤔 I couldn't find the same issue with other projects. The workaround is registering a dummy resource in the empty resource group. On the other hand, I didn't find any mentions that such custom API server behavior is not allowed. Didn't dig too deep, though.

While I was able to quickly implement a workaround on our end (see the changes: https://github.com/kubeshop/botkube/compare/main...pkosiec:empty-resource-list-workaround?expand=1), this doesn't look right (and it's ugly because of the string comparison). So I'm not sure if we should apply it on our side, if this is not an error on our (K8s API consumers) side 🤔 

As I have mixed feeling, I need some advice 😄 @huseyinbabal what do you think? Should we apply [the workaround](https://github.com/kubeshop/botkube/compare/main...pkosiec:empty-resource-list-workaround?expand=1) or not?

**Comment by nguyend91** [comment]
So we _did_ implement a workaround on our end, by creating a mock `botkube-autoscaler` (that frankly will never scale), but just wanted to give y'all the heads up for any future issues.

```
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: botkube-autoscaler
  namespace: botkube
spec:
  maxReplicaCount: 1
  scaleTargetRef:
    name: botkube
  triggers:
    - type: new-relic
      metadata:
        account: {{ .Values.newrelic.account | quote }}
        queryKey: {{ .Values.newrelic.apikey | quote }}
        region: "US"
        noDataError: "true"
        nrql: "FROM Metric SELECT average(k8s.container.cpuCoresUtilization) AS 'CPU utilization (%)' WHERE k8s.clusterName = 'eks-stage' AND k8s.namespaceName = 'botkube' TIMESERIES"
        threshold: "100"
        activationThreshold: "100"
```

I appreciate you looking at this, though.
