### ISSUE TITLE
Generic filters for reasons and/or messages

### ISSUE THREAD

**Issue by bygui86** [kubeshop/botkube#835]
## Overview

It would be nice to have a simple, generic configuration to filter out events I'm not interested in, the same way it's possible to filter different event types (created, update, error, etc). Maybe using regex.

For example **_I'm interested_** in following K8s Nodes events:
![Screenshot 2022-11-07 at 09 17 02](https://user-images.githubusercontent.com/22518997/200262020-8a0c0e75-8985-4742-9103-c4039a36c896.png)

But **_I'm not interested_** in following K8s Nodes events:
![Screenshot 2022-11-07 at 09 12 42](https://user-images.githubusercontent.com/22518997/200262004-647c1893-499d-42e2-a55e-dc82bd0147af.png)
![Screenshot 2022-11-07 at 09 12](https://user-images.githubusercontent.com/22518997/200262011-5c5736bd-357c-4b54-8f0b-bbb3fcaef367.png)

Or regarding K8s Pods, **_I'm interested_** in:
![Screenshot 2022-11-07 at 09 14 09](https://user-images.githubusercontent.com/22518997/200262520-c5bce3c2-1c8d-49df-bf35-40b869ee511a.png)

But **_I'm not interested_** in:
![Screenshot 2022-11-07 at 09 13 52](https://user-images.githubusercontent.com/22518997/200262638-41a2f151-178e-4da1-b708-bd6c82e86356.png)

Example of YAML configuration:

```yml
global_config.yaml: |  sources:
    nodes:
      displayName: "K8s Nodes"
      kubernetes:
        events:
          - all
        namespaces:
          include:
            - ".*"
        filters:
          messages:
            include:
              - "cgroup out of memory"
            exclude:
              - "failed to garbage collect"
          reasons:
            include:
              - OOMKilled
            exclude:
              - FreeDiskSpaceFailed
        resources:
          - name: v1/nodes
            updateSetting:
              includeDiff: true
            filters:
              messages:
                include:
                  - "cgroup out of memory"
                exclude:
                  - "failed to garbage collect"
              reasons:
                include:
                  - OOMKilled
                exclude:
                  - FreeDiskSpaceFailed
```

## Acceptance Criteria

- filters can be applied to event `reason` or `message`
- filters on `messages` must be:
  - case insensitive
  - a regex
- filters on `reasons` must be:
  - case insensitive
  - fully specified reason (e.g. OOMKilled, FreeDiskSpaceFailed)
- if no filters are specified at any level of the `source`, then the default behaviour is `include all`
- filters can be defined in the YAML configuration, at `source` level and/or at `resources` level, same as `namespaces` and `events` (see YAML config example above)

## Reason

The [filters](https://docs.botkube.io/usage/filters/) feature is nice, but it's pretty tricky, hard and time consuming to develop a filter for each K8s resource and CRD or develop a generic filter for all K8s resources and CRDs.
