### ISSUE TITLE
Release Botkube 0.16

### ISSUE THREAD

**Issue by pkosiec** [kubeshop/botkube#851]
## Overview

This task aggregates all the to-dos which should be done when it comes to 0.16 release.

## AC
- [x] Go through the release process instruction and release new Botkube (https://docs.botkube.io/community/contribute/release)
- [x] Describe any breaking changes in the GitHub release
     - Include: https://github.com/kubeshop/botkube/pull/850
- [x] Test the release candidate. Include:
    - Manual tests for Slack interactivity
    - Test telemetry
    - Aggregate and coordinate the manual testing described previously (e.g. https://github.com/kubeshop/botkube/issues/741#issuecomment-1263443042)
    - Testing scenario - you can use: https://github.com/kubeshop/botkube/issues/595#issuecomment-1225458097
- [ ] Schedule all community activities - blog post, sharing the news in social media, livestream, etc. (@brampling)

**Comment by pkosiec** [comment]
## Release activities

-  Ensure that all security vulnerabilities are fixed or mitigated                                                                                       
  - assignee: 

- [ ] Cut initial release candidate  for`v0.16.0`
  - assignee: @pkosiec

- Finalize release the `v0.16.0`
  - assignee: @pkosiec

- Test Slack  (RTM)
    - assignee: CI
    - it's tested as a part of CI.

- [ ] Test Slack  (Socket)
    - test all interactive buttons/modals
    - assignee: @pkosiec - will test it as a part of interactivity test

- [ ] Test Mattermost
    - assignee:
 
- Test Discord
    - assignee:  CI
    - it's tested as a part of CI.
    - [ ] manual tests @pkosiec - will test it as a part of interactivity test

-  [ ] Test MS Teams   
    - assignee:
    
-  [ ] Test Elasticsearch
    - assignee:

-  [ ] Test Webhook
    - assignee:

-  [ ] Test Telemetry
    - assignee: 

- Check if we described all breaking changes in the release summary and if it's rendered correctly. 
  - assignee: team

**Others**
- ⏳ Prepare the release notes                                                                                                                             
  - assignee: @brampling 
- ⏳ Create a blog post and cross-post it (e.g. Medium, Dev.to)                                                                                            
  - assignee: @brampling 
- ⏳ Share the news on social media (e.g. Reddit, Hacker News, LinkedIn, Twitter, Slack)                                                                   
  - assignee: @brampling

**Comment by pkosiec** [comment]
Testing scenario: https://github.com/kubeshop/botkube/issues/595#issuecomment-1225458097

## Event constraints


Ensure you have the following sources in local config:

```yaml
communications:
  'default-group':
    # Settings for Slack
    socketSlack:
      enabled: true
      appToken: # TODO: ...
      botToken: # TODO: ...
      notification:
        type: "short"
      channels:
        'default':
          name: botkube-demo
          bindings:
            executors:
              - kubectl-read-only
            sources:
              - pod-label
              - pod-annotation
              - pod-name
              - event-reason
              - event-message

sources:
  'pod-label':
     kubernetes:
       namespaces:
         include:
           - ".*"
       event:
         types:
           - create
           - delete
           - error
       labels:
         my-label: "true"
       resources:
         - type: v1/pods
  'pod-annotation':
     kubernetes:
       namespaces:
         include:
           - ".*"
       event:
         types:
          - create
          - delete
          - error
       annotations:
        my-annotation: "false"
       resources:
        - type: v1/pods
          annotations:
            my-annotation: "true" # override
  'pod-name':
    kubernetes:
      namespaces:
        include:
          - ".*"
      event:
        types:
          - create
          - delete
          - error
      resources:
        - type: v1/pods
          name: "^my.*"
  'event-reason':
    kubernetes:
      annotations:
        event-reason-constraints: "true"
      namespaces:
        include:
          - ".*"
      event:
        types:
          - create
          - delete
          - error
      resources:
        - type: v1/pods
          event:
            reason: "^BackOff$"
  'event-message':
    kubernetes:
      annotations:
        event-message-constraints: "true"
      namespaces:
        include:
          - ".*"
      event:
        message: "^Back-off .*"
        types:
          - create
          - delete
          - error
      resources:
        - type: v1/pods
actions:
  'get-created-resource':
    enabled: true
    displayName: "Get resource"
    command: "kubectl get {{ .Event.TypeMeta.Kind | lower }}{{ if .Event.Namespace }} -n {{ .Event.Namespace }}{{ end }} {{ .Event.Name }}"
    bindings:
      sources:
        - pod-label
        - pod-annotation
        - pod-name
        - event-reason
        - event-message
      executors:
        - kubectl-read-only
``` 

Install Botkube.

Apply the following yaml and see if you were notified about proper events:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: pod-labeled
  labels:
    my-label: "true"
spec:
  containers:
  - name: nginx
    image: nginx:stable
    command: ["foo"]
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-not-labeled
  labels:
    my-label: "false"
spec:
  containers:
  - name: nginx
    image: nginx:stable
    command: ["foo"]
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-annotated
  annotations:
    my-annotation: "true"
spec:
  containers:
  - name: nginx
    image: nginx:stable
    command: ["foo"]
---
apiVersion: v1
kind: Pod
metadata:
  name: bar
  annotations:
    my-annotation: "false"
spec:
  containers:
  - name: nginx
    image: nginx:stable
    command: ["foo"]
---
apiVersion: v1
kind: Pod
metadata:
  name: my-name
spec:
  containers:
  - name: nginx
    image: nginx:stable
    command: ["foo"]
---
apiVersion: v1
kind: Pod
metadata:
  name: not-my-name
spec:
  containers:
  - name: nginx
    image: nginx:stable
    command: ["foo"]
---
apiVersion: v1
kind: Pod
metadata:
  name: event-reason-constraints
  annotations:
    event-reason-constraints: "true"
spec:
  containers:
  - name: nginx
    image: nginx:stable
    command: ["foo"]
---
apiVersion: v1
kind: Pod
metadata:
  name: event-message-constraints
  annotations:
    event-message-constraints: "true"
spec:
  containers:
  - name: nginx
    image: nginx:stable
    command: ["foo"]    
```

## Automation

1. Run `@Botkube list actions`
2. Run `@Botkube enable action describe-created-resource` 
3. Create new resource from Terminal:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: failing
spec:
  containers:
  - name: nginx
    image: nginx:latest
    command: ["foo"]
```

Delete the resource from Terminal

4. Run `@Botkube disable action describe-created-resource` 

Create the same resource
