### ISSUE TITLE
Validate plugins entities

### ISSUE THREAD

**Issue by mszostok** [kubeshop/botkube#869]
## Overview

We added new entities:
- Plugin index entries
- Source plugin
- Executor plugin

As a result, we need to introduce at least basic validation to make sure that:

1. Entries define in the index files don't conflict with each other - having the same `name`, `type` and `version`:

   <details>
     <summary>Example</summary>

   ```yaml
   entries:
     - name: "kubectl"
       type: "executor"
       description: "Kubectl executor plugin."
       version: "v1.0.0"
       urls:
         - url: https://github.com/kubeshop/botkube/releases/download/v0.17.0/source_kubernetes-darwin-amd64
           platform:
             architecture: amd64
             os: darwin
     - name: "kubectl"
       type: "executor"
       description: "Kubectl executor plugin."
       version: "v1.0.0"
       urls:
         - url: https://github.com/kubeshop/botkube/releases/download/v0.16.0/source_kubernetes-darwin-amd64
           platform:
             architecture: amd64
             os: darwin
   ```
   </details>

2. Enabled executors don't conflict with each other:
   <details>
     <summary>Example</summary>

   ```yaml
   executors:
     'plugin-based':
       botkube/kubectl:
         enabled: true
         config:
           namespaces:
             include: ["botkube", "default","ambassador"]
           commands:
             verbs: ["get","logs","top"]
             resources: ["pods","deployments","nodes","configmap"]
       mszostok/kubectl:  # not allowed as it is conflicting with already registered 'kubectl' from the Botkube repository.
         enabled: true
         config:
           commands:
             verbs: ["get","logs","top"]
   ```
   ```yaml
   executors:
     'plugin-based':
       botkube/kubectl@v1.0.0:
         enabled: true
         config:
           namespaces:
             include: ["botkube", "default","ambassador"]
           commands:
             verbs: ["get","logs","top"]
             resources: ["pods","deployments","nodes","configmap"]
       botkube/kubectl@v1.2.0:  # not allowed as it is conflicting with already registered 'kubectl' from the Botkube repository in different version.
         enabled: true
         config:
           commands:
             verbs: ["get","logs","top"]
   ```
   </details>

3. We cannot have bindings to the same executor but from different repositories or versions:
   <details>
     <summary>Example</summary>

   ```yaml
   communications:
     default-group:
       socketSlack:
         enabled: true
         channels:
           default:
             name: botkubers
             bindings:
               executors:            # such binding is not allowed as it has conflicting 'kubectl' executor from different repositories
                 - kubectl-read-only
                 - kubectl-pods-rw
   executors:
     'kubectl-read-only':
       botkube/kubectl:
         enabled: true
         config:
           # ...
     'kubectl-pods-rw':
       mszostok/kubectl:
         enabled: true
         config:
           # ...
     'kubectl-deploy-rw':
       botkube/kubectl@v1.0.0:
         enabled: true
         config:
           # ...
   ```
   </details>

## Acceptance criteria
- User-friendly errors are returned when Botkube starts with wrong configuration
- Validator is covered with unit test cases 

## Reason

It's normal that our end-user may misconfigure enabled plugins. We should provide a basic validation to help them understand what is wrong with defined configuration.
