### ISSUE TITLE
Add support for the `aliases` property for executor plugins

### ISSUE THREAD

**Issue by mszostok** [kubeshop/botkube#870]
## Overview

Currently, the aliases are built-in into Botkube core logic. We should support setting them in the YAML configuration too:
```yaml
aliases: # shortcuts
  kc: 
     command: kubectl
     displayName: "...." # optional field
  kgp:
     command: kubectl get pod
````

With such configuration, the`kubectl` executor plugin can be used with the following command prefixes: `kubectl`, `kc`. Additionally, `kgp` resolves to the whole command that was defined.

## Acceptance Criteria

- end user can define executor aliases
- update documentation
- add e2e test
- list possible aliases under `list executors`

## Reason

Simplify typing plugin executor in chat window.

**Comment by mszostok** [comment]
Double check before doing the implementation whether we should 
- allowing to set the alias for a whole command definition e.g. `kcp=kubectl get pod`
- having them global per cluster

**Comment by mszostok** [comment]
Questions:
- should we also support `displayName`/`description` to support less experienced k8s users. Based on e.g dispaly Name they could figure it out what a given command does and know that they should run it.

- should we support global aliases, or aliases per cluster?

**Global aliases:**
```yaml
executors:
  'team-a-kubectl':
    botkube/kubectl@v1.0.0:
      enabled: true
      config: ... 
         

  'team-b-kubectl':
    botkube/kubectl@v1.0.0:
      enabled: true
      config: ...

communications:
  default-group:
    socketSlack:
      enabled: true
      channels:
        all:
          name: all
          bindings:
            executors:
              - plugin-kubectl 

aliases: # shortcuts
  kc: kubectl
  kgp: kubectl get pod
```
**Executor aliases:**

```yaml
executors:
  'team-a-kubectl':
    botkube/kubectl@v1.0.0:
      enabled: true
      config: ...     
      aliases:  &aliases
         kc: kubectl # displayName/description?
         kcg: kubectl get pod
         

  'team-b-kubectl':
    botkube/kubectl@v1.0.0:
      enabled: true
      config: ...
      aliases: *aliases

communications:
  default-group:
    socketSlack:
      enabled: true
      channels:
        all:
          name: all
          bindings:
            executors:
              - plugin-kubectl 
```
