### ISSUE TITLE
Add Botkube plugin release job

### ISSUE THREAD

**Issue by mszostok** [kubeshop/botkube#871]
### Releasing Botkube plugins

As a part of 0.17 release, such binaries should be added to the GitHub release assets:

- `plugins-index.yaml`
- `source_kubernetes-darwin-amd64`
- `source_kubernetes-linux-amd64`
- `executor_kubectl-darwin-amd64`
- `executor_kubectl-linux-amd64`

Where the `plugins-index.yaml` is defined as follows:

```yaml
entries:
  - name: "kubectl"
    type: "executor"
    description: "Kubectl executor plugin."
    version: "v1.0.0"
    urls:
      - url: https://github.com/kubeshop/botkube/releases/download/v0.17.0/executor_kubectl-darwin-amd64
        platform:
          architecture: amd64
          os: darwin
      - url: https://github.com/kubeshop/botkube/releases/download/v0.17.0/executor_kubectl-darwin-arm64
        platform:
          architecture: arm64
          os: darwin
      - url: https://github.com/kubeshop/botkube/releases/download/v0.17.0/executor_kubectl-linux-amd64
        platform:
          architecture: amd64
          os: linux
      - url: https://github.com/kubeshop/botkube/releases/download/v0.17.0/executor_kubectl-linux-arm64
        platform:
          architecture: arm64
          os: linux
  - name: "kubernetes"
    type: "source"
    description: "Kubernetes source plugin."
    version: "v1.0.0"
    urls:
      - url: https://github.com/kubeshop/botkube/releases/download/v0.17.0/source_kubernetes-darwin-amd64
        platform:
          architecture: amd64
          os: darwin
      - url: https://github.com/kubeshop/botkube/releases/download/v0.17.0/source_kubernetes-darwin-arm64
        platform:
          architecture: arm64
          os: darwin
      - url: https://github.com/kubeshop/botkube/releases/download/v0.17.0/source_kubernetes-linux-amd64
        platform:
          architecture: amd64
          os: linux
      - url: https://github.com/kubeshop/botkube/releases/download/v0.17.0/source_kubernetes-linux-arm64
        platform:
          architecture: arm64
          os: linux
```

The index file can be generated automatically just by scanning the directory where plugins binaries are stored.

## Acceptance Criteria

- Release all available plugins as a part of automated release process
  - source binaries
  - executor binaries
  - index.yaml
- Support patch releases too
- Provide an example of successful release done on your fork
- Update release documentation: https://docs.botkube.io/community/contribute/release
