### ISSUE TITLE
400 Bad request for ELS - v8.5.2

### ISSUE THREAD

**Issue by sumeet-zuora** [kubeshop/botkube#887]
## Description

Trying to integrate, Elasticsarch with botkube, it was able to create index with empty mapping not sure if that is right? but it cannot send events to Elastic.. receive 400 

## Expected behavior

Message gets sent to ELasticsearch

## Actual behavior

```
time="2022-12-15T03:56:22Z" level=debug msg=">> Sending to Elasticsearch: {TypeMeta:{Kind:Deployment APIVersion:apps/v1} ObjectMeta:{Name:karpenter GenerateName: Namespace:karpenter SelfLink: UID: ResourceVersion:33667626 Generation:3 CreationTimestamp:2022-12-13 01:14:59 +0000 UTC DeletionTimestamp:<nil> DeletionGracePeriodSeconds:<nil> Labels:map[app:karpenter app.kubernetes.io/instance:karpenter app.kubernetes.io/managed-by:Helm app.kubernetes.io/name:karpenter app.kubernetes.io/version:0.20.0 helm.sh/chart:karpenter-v0.20.0 helm.toolkit.fluxcd.io/name:karpenter helm.toolkit.fluxcd.io/namespace:karpenter] Annotations:map[deployment.kubernetes.io/revision:3 meta.helm.sh/release-name:karpenter meta.helm.sh/release-namespace:karpenter] OwnerReferences:[] Finalizers:[] ManagedFields:[{Manager:helm-controller Operation:Update APIVersion:apps/v1 Time:2022-12-13 17:18:05 +0000 UTC FieldsType:FieldsV1 FieldsV1:{\"f:metadata\":{\"f:annotations\":{\".\":{},\"f:meta.helm.sh/release-name\":{},\"f:meta.helm.sh/release-namespace\":{}},\"f:labels\":{\".\":{},\"f:app\":{},\"f:app.kubernetes.io/instance\":{},\"f:app.kubernetes.io/managed-by\":{},\"f:app.kubernetes.io/name\":{},\"f:app.kubernetes.io/version\":{},\"f:helm.sh/chart\":{},\"f:helm.toolkit.fluxcd.io/name\":{},\"f:helm.toolkit.fluxcd.io/namespace\":{}}},\"f:spec\":{\"f:progressDeadlineSeconds\":{},\"f:replicas\":{},\"f:revisionHistoryLimit\":{},\"f:selector\":{},\"f:strategy\":{\"f:rollingUpdate\":{\".\":{},\"f:maxSurge\":{},\"f:maxUnavailable\":{}},\"f:type\":{}},\"f:template\":{\"f:metadata\":{\"f:annotations\":{\".\":{},\"f:prometheus.io/path\":{},\"f:prometheus.io/port\":{},\"f:prometheus.io/scrape\":{}},\"f:labels\":{\".\":{},\"f:app.kubernetes.io/instance\":{},\"f:app.kubernetes.io/name\":{}}},\"f:spec\":{\"f:affinity\":{\".\":{},\"f:nodeAffinity\":{\".\":{},\"f:requiredDuringSchedulingIgnoredDuringExecution\":{}},\"f:podAntiAffinity\":{\".\":{},\"f:requiredDuringSchedulingIgnoredDuringExecution\":{}}},\"f:containers\":{\"k:{\\\"name\\\":\\\"controller\\\"}\":{\".\":{},\"f:env\":{\".\":{},\"k:{\\\"name\\\":\\\"KARPENTER_SERVICE\\\"}\":{\".\":{},\"f:name\":{},\"f:value\":{}},\"k:{\\\"name\\\":\\\"KUBERNETES_MIN_VERSION\\\"}\":{\".\":{},\"f:name\":{},\"f:value\":{}},\"k:{\\\"name\\\":\\\"MEMORY_LIMIT\\\"}\":{\".\":{},\"f:name\":{},\"f:valueFrom\":{\".\":{},\"f:resourceFieldRef\":{}}},\"k:{\\\"name\\\":\\\"SYSTEM_NAMESPACE\\\"}\":{\".\":{},\"f:name\":{},\"f:valueFrom\":{\".\":{},\"f:fieldRef\":{}}},\"k:{\\\"name\\\":\\\"WEBHOOK_PORT\\\"}\":{\".\":{},\"f:name\":{},\"f:value\":{}}},\"f:image\":{},\"f:imagePullPolicy\":{},\"f:livenessProbe\":{\".\":{},\"f:failureThreshold\":{},\"f:httpGet\":{\".\":{},\"f:path\":{},\"f:port\":{},\"f:scheme\":{}},\"f:initialDelaySeconds\":{},\"f:periodSeconds\":{},\"f:successThreshold\":{},\"f:timeoutSeconds\":{}},\"f:name\":{},\"f:ports\":{\".\":{},\"k:{\\\"containerPort\\\":8080,\\\"protocol\\\":\\\"TCP\\\"}\":{\".\":{},\"f:containerPort\":{},\"f:hostPort\":{},\"f:name\":{},\"f:protocol\":{}},\"k:{\\\"containerPort\\\":8081,\\\"protocol\\\":\\\"TCP\\\"}\":{\".\":{},\"f:containerPort\":{},\"f:hostPort\":{},\"f:name\":{},\"f:protocol\":{}},\"k:{\\\"containerPort\\\":8443,\\\"protocol\\\":\\\"TCP\\\"}\":{\".\":{},\"f:containerPort\":{},\"f:hostPort\":{},\"f:name\":{},\"f:protocol\":{}}},\"f:readinessProbe\":{\".\":{},\"f:failureThreshold\":{},\"f:httpGet\":{\".\":{},\"f:path\":{},\"f:port\":{},\"f:scheme\":{}},\"f:periodSeconds\":{},\"f:successThreshold\":{},\"f:timeoutSeconds\":{}},\"f:resources\":{\".\":{},\"f:limits\":{\".\":{},\"f:cpu\":{},\"f:memory\":{}},\"f:requests\":{\".\":{},\"f:cpu\":{},\"f:memory\":{}}},\"f:terminationMessagePath\":{},\"f:terminationMessagePolicy\":{}}},\"f:dnsPolicy\":{},\"f:hostNetwork\":{},\"f:nodeSelector\":{},\"f:priorityClassName\":{},\"f:restartPolicy\":{},\"f:schedulerName\":{},\"f:securityContext\":{\".\":{},\"f:fsGroup\":{}},\"f:serviceAccount\":{},\"f:serviceAccountName\":{},\"f:terminationGracePeriodSeconds\":{},\"f:tolerations\":{},\"f:topologySpreadConstraints\":{\".\":{},\"k:{\\\"topologyKey\\\":\\\"topology.kubernetes.io/zone\\\",\\\"whenUnsatisfiable\\\":\\\"ScheduleAnyway\\\"}\":{\".\":{},\"f:labelSelector\":{},\"f:maxSkew\":{},\"f:topologyKey\":{},\"f:whenUnsatisfiable\":{}}}}}}} Subresource:} {Manager:kube-controller-manager Operation:Update APIVersion:apps/v1 Time:2022-12-15 03:56:22 +0000 UTC FieldsType:FieldsV1 FieldsV1:{\"f:metadata\":{\"f:annotations\":{\"f:deployment.kubernetes.io/revision\":{}}},\"f:status\":{\"f:availableReplicas\":{},\"f:conditions\":{\".\":{},\"k:{\\\"type\\\":\\\"Available\\\"}\":{\".\":{},\"f:lastTransitionTime\":{},\"f:lastUpdateTime\":{},\"f:message\":{},\"f:reason\":{},\"f:status\":{},\"f:type\":{}},\"k:{\\\"type\\\":\\\"Progressing\\\"}\":{\".\":{},\"f:lastTransitionTime\":{},\"f:lastUpdateTime\":{},\"f:message\":{},\"f:reason\":{},\"f:status\":{},\"f:type\":{}}},\"f:observedGeneration\":{},\"f:readyReplicas\":{},\"f:replicas\":{},\"f:unavailableReplicas\":{},\"f:updatedReplicas\":{}}} Subresource:status}]} Code: Title:apps/v1/deployments updated Name:karpenter Namespace:karpenter Messages:[status.availableReplicas:\n\t-: 2\n\t+: 1\n] Type:update Reason: Error: Level:warn Cluster:eks-tools-uw2-na-dev-01 Channel: TimeStamp:2022-12-15 03:56:22.07339317 +0000 UTC m=+390.529566776 Count:0 Action: Skip:false Resource:apps/v1/deployments Object:0xc000012718 Recommendations:[] Warnings:[] Actions:[]}" commGroup=default-group sink=Elasticsearch
time="2022-12-15T03:56:22Z" level=error msg="while sending event: 1 error occurred:\n\t* while sending event to Elasticsearch index \"botkube\": while posting data to ELS: elastic: Error 400 (Bad Request)" component=Controller
```

## Steps to reproduce

Configure ELS .. and Elastic version is 8.5.2

**Comment by sumeet-zuora** [comment]
Sure, 

error
```
time="2022-12-15T12:46:04Z" level=error msg="while sending event: 1 error occurred:\n\t* while sending event to Elasticsearch index \"botkube\": while posting data to ELS: elastic: Error 400 (Bad Request)" component=Controller
time="2022-12-15T12:50:31Z" level=error msg="while sending event: 1 error occurred:\n\t* while sending event to Elasticsearch index \"botkube\": while posting data to ELS: elastic: Error 400 (Bad Request)" component=Controller
```

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: botkube
  namespace: botkube
  labels:
    environment: "${cluster_env:=dev}"
    region: "${cluster_region}"
    cluster_name: "${cluster_name}"
    account_id: "${account_id}"
spec:
  releaseName: botkube
  chart:
    spec:
      chart: botkube
      version: "v0.16.0"
      sourceRef:
        kind: HelmRepository
        name: botkube
        namespace: flux-system
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    executors:
      kubectl-read-only:
        kubectl:
          enabled: true
    settings:
      # -- Cluster name to differentiate incoming messages.
      clusterName: "${cluster_name}"
      log:
        # -- Sets one of the log levels. Allowed values: `info`, `warn`, `debug`, `error`, `fatal`, `panic`.
        level: info
        disableColors: true
    communications:
      default-group:
        socketSlack:
          enabled: true
          ## Format: channels.{alias}
          channels:
            'default':
              name: 'k8-alerts'
              bindings:
                executors:
                  - kubectl-read-only
                sources:
                  - k8s-err-events
                  - k8s-err-with-logs-events
                  - k8s-create-events
                  - k8s-recommendation-events
          notification:
            # -- Configures notification type that are sent. Possible values: `short`, `long`.
            type: short
        elasticsearch:
          enabled: true
          server: 'https://elasticsearch.${tools_cluster_for_this_environment}
          username: 'botkube'
          skipTLSVerify: true
          indices:
            'default':
              name: botkube
              type: botkube-event
              shards: 1
              replicas: 0
              bindings:
                sources:
                  - k8s-all-events
                  - k8s-err-events
                  - k8s-err-with-logs-events
                  - k8s-create-events
                  - k8s-recommendation-events

```
