### ISSUE TITLE
Add plugin dependency management into Botkube

### ISSUE THREAD

**Issue by mszostok** [kubeshop/botkube#899]
## Overview

Add plugin dependency management into Botkube. The `MetadataOutput` should support specifying a list of binaries (in different os/arch) that are a dependency for a given plugin. This should be included in the generated plugin index YAML file.

```yaml
entries:
  - name: "helm"
    type: "executor"
    description: "Helm executor plugin."
    version: "v1.0.0"
    urls:
      - url: https://github.com/kubeshop/botkube/releases/download/v0.17.0/executor_helm-darwin-amd64
        dependencies:
           helm:
              url: https://github.com/kubeshop/botkube/releases/download/v0.17.0/helm-darwin-amd64
        platform:
          os: darwin
          architecture: amd64
      - url: https://github.com/kubeshop/botkube/releases/download/v0.17.0/executor_helm-darwin-arm64
        dependencies:
          helm: https://github.com/kubeshop/botkube/releases/download/v0.17.0/helm-darwin-amd64
        platform:
          os: darwin
          architecture: arm64
      - url: https://github.com/kubeshop/botkube/releases/download/v0.17.0/executor_helm-linux-amd64
        dependencies:
          helm: https://github.com/kubeshop/botkube/releases/download/v0.17.0/helm-darwin-amd64
        platform:
          os: linux
          architecture: amd64
      - url: https://github.com/kubeshop/botkube/releases/download/v0.17.0/executor_helm-linux-arm64
        dependencies:
          helm: https://github.com/kubeshop/botkube/releases/download/v0.17.0/helm-darwin-amd64
        platform:
          os: linux
          architecture: arm64
```

Botkube should collect all dependencies of enabled plugins and install all required binaries.
