### ISSUE TITLE
Release Botkube v1.0

### ISSUE THREAD

**Issue by pkosiec** [kubeshop/botkube#972]
## Overview

This task aggregates all the to-dos which should be done when it comes to the release.

## AC
- [ ] Go through the release process instruction and release new Botkube (https://docs.botkube.io/community/contribute/release)
- [ ] Describe any breaking changes in the GitHub release (see the issues with `breaking` label)
- [ ] Test the release candidate. Include:
    - Manual tests for Slack interactivity
    - Test telemetry
    - Aggregate and coordinate the manual testing described previously (e.g. https://github.com/kubeshop/botkube/issues/904, https://github.com/kubeshop/botkube/issues/957)
- [ ] Schedule all community activities - blog post, sharing the news in social media, livestream, etc. (@brampling)

**Comment by mszostok** [comment]
Breaking changes:
- `notification: short/long` was removed, it's up to the plugin to return a suitable message.

**Comment by huseyinbabal** [comment]
Breaking Changes:
- `kubernetes` configuration is named as `botkube/kubernetes`
- `filters` configuration is removed from main configuration, now it is under Kubernetes source plugin.
### Before:
```yaml
# ...trimmed
filters:
  kubernetes:
    objectAnnotationChecker: true
    nodeEventsChecker: true
#...trimmed
```
### After:
```yaml
...trimmed
 'k8s-all-events':
    displayName: "Kubernetes Info"
    botkube/kubernetes:
      enabled: true
      config:
        filters:
          kubernetes:
            objectAnnotationChecker: true
            nodeEventsChecker: true
# ...trimmed
```
