### ISSUE TITLE
Botkube cannot find helm executable

### ISSUE THREAD

**Issue by gitbluf** [kubeshop/botkube#987]
## Description

Botkube version: v0.18.0

## Expected behavior

Botkube executes helm commands

## Actual behavior

Botkube returns:

`exec: "helm": executable file not found in $PATH`

List executors returns:
```
EXECUTOR     ENABLED ALIASES
botkube/helm true    
kubectl      true    k, kc
```

## Steps to reproduce
Deploy botkube with  following values.

Plugins:
```
    plugins:
      repositories:
        botkube:
          url: https://github.com/kubeshop/botkube/releases/download/v0.17.0/plugins-index.yaml
```
executors:
```
    executors:
      helm:
        botkube/helm:
          enabled: true
          config:
            helmCacheDir: /tmp/helm/.cache
            helmConfigDir: /tmp/helm/
            helmDriver: secret
          context: &defaultExecutorContext
```
communicataion:
```
    communications:
      default-group:
        socketSlack:
          enabled: true
          botToken: xoxb-.......
          appToken: xapp-.......
          notification:
            type: long
          channels:
            default:
              name: infra-channel
              notification:
                disabled: false
              bindings:
                executors:
                  - kubectl-write
                  - helm
                sources:
                  - k8s-err-events
                  - k8s-recommendation-events
```

Additonal:
- kubectl works as exected

**Comment by mszostok** [comment]
Hi @gitbluf 

The issue is that you use the Botkube in version **0.18** and plugin repository from **0.17** (https://github.com/kubeshop/botkube/releases/download/v0.17.0/plugins-index.yaml). They are not compatible. In the 0.18 Botkube core downloads necessary plugin dependencies based on the metadata defined in the `plugin-index.yaml`.

```yaml
    - name: helm
      type: executor
      description: Helm is the Botkube executor plugin that allows you to run the Helm CLI commands directly from any communication platform.
      version: v0.18.0
      urls:
        - url: https://github.com/kubeshop/botkube/releases/download/v0.18.0/executor_helm_darwin_amd64
          platform:
            os: darwin
            architecture: amd64
          dependencies:
            helm:
                url: https://get.helm.sh/helm-v3.6.3-darwin-amd64.tar.gz//darwin-amd64
# ....
```

In the 0.17 index file the `dependencies`, so Botkube doesn't download the `helm` CLI dependency. As a result, you get `exec: "helm": executable file not found in $PATH`


Please use `https://github.com/kubeshop/botkube/releases/download/v0.18.0/plugins-index.yaml`  instead. Valid config:
```yaml
    plugins:
      repositories:
        botkube:
          url: https://github.com/kubeshop/botkube/releases/download/v0.18.0/plugins-index.yaml
```
